# Generated by Django 3.1.7 on 2021-03-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='api_group',
            new_name='group',
        ),
    ]
